[package]
name = "engine-bench"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Benchmarks for the matching engine."

[dependencies]
engine-types = { workspace = true }
engine-core = { workspace = true }
rand = { workspace = true }
criterion = { workspace = true }

[[bench]]
name = "matching"
harness = false
